### PR TITLE
Fixing bugs in bot due to change in CSS

### PR DESCRIPTION
**Pull request by preetishkakkar**

### CODE REVIEW

**Comment by NelsonGaldeman** [comment]
Thanks for the update! I've read it fast and looks good. I will do some tests this night and merge it.

**Comment by Julian1104** [comment]
Hello NelsonGaldeman how are you?, Do you have news about update?

**Comment by Julian1104** [comment]
VM1938:141 Uncaught TypeError: Cannot set property 'innerHTML' of null
    at sendMessage (<anonymous>:141:61)
    at start (<anonymous>:232:4)

I HAVE THIS ERROR, SORRY MY QUESTION BUT I AM NOT DEVELOPER!

**Comment by NelsonGaldeman** [comment]
Please read https://github.com/bruno222/whatsapp-web-bot/issues/22

**Pull request closed without merging**
