### PR TITLE
New method to get active chat name

### PR DESCRIPTION
**Pull request by NelsonGaldeman**
I get the whole chat list and check which one has the "active" class then I get the name. If any of them is active, then the name is "undefined". It's a more stable way to compare titles on the "selectChat" function.

### CODE REVIEW

**Comment by bruno222** [comment]
Gracias, Nelson! 👍  Whenever you come to Florianopolis, let me know - I own you a beer for keeping this repo updated. Thank you!

**Comment by bruno222** [comment]
Just added you as collaborator, so you don't have to wait for me to approve your PR.

**Comment by NelsonGaldeman** [comment]
@bruno222 What a coincidence, I'm planning going to Florianopolis this year xD Not sure if I will go yet.

I may use this for my work so it's a good idea to keep it updated. It's an interesting idea with a lot of potential. It could also get data from an external server with a cross-origin ajax request.

**Comment by bruno222** [comment]
Cool, Nelson! If you are really come, let me know!

Yes, I agree, a business logic to (1) get all received messages, (2) send to a server to process and them (3) reply back would be an awesome feature, for sure!

See you!

**Comment by bruno222** [comment]
Nelson,

I have got a potential client who wants exactly this: This bot integrated with their APIs (to send/reveive messages). Are you interested to get this project? Do you have time?

I am asking because I do no have time (I am moving to Munich to work in another company soon, I can't build and maintain the code for them)

If you got interested, let me know! Let's talk on private for now on if you get interested, my email is bruno222 arroba email del google

Cheers!

**Pull request merged**
